name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git config user.email "welldey102@gmail.com" && git config user.name "randy102" && git add -A && git commit -m "Updated code"
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "petland-admin" #Must be unique in Heroku
          heroku_email: "welldey102@gmail.com"
